ardc/ardc/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls import url
from core.ajax import get_municipios, get_info, get_last, get_detalle

urlpatterns = [
    #Paths del core
    path('', views.filtrar, name = "Filtrar"),
    path('agregar/',views.agregar, name = "Agregar Infromacion"),
    path('detalle/',views.detalleBeneficiario, name = "Agregar Ayuda"),
    path('actualizar/', views.actualizar, name = "actualizar"),
    #path('iniciar/', views.iniciar, name = "Iniciar Sesion"),
    #Admin
    path('admin/', admin.site.urls),
    url(r'ajax/get_municipios', get_municipios, name='get_municipios'),
    url(r'ajax/get_info', get_info, name='get_info'),
    url(r'ajax/get_last', get_last, name='get_last'),
    url(r'ajax/get_detalle', get_detalle, name='get_detalle'),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('iniciar/', views.login, name = "Iniciar Sesion"),
    path('logout/', views.logout),
]

ardc/core/models.py
from django.db import models
from django.conf import settings
from datetime import datetime

# Create your models here.

class Departamento(models.Model):
    idDepartamento = models.CharField(max_length=10,primary_key=True)
    nombre_departamento = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_departamento

class Municipio(models.Model):
    idMunicipio = models.CharField(max_length=10,primary_key=True)
    departamento = models.ForeignKey(Departamento, null = True, blank = True, on_delete=models.CASCADE)
    nombre_municipio = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre_municipio

class Usuario(models.Model):
    idUsuario = models.CharField(max_length=10,primary_key=True)
    usuario = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nombre_usuario = models.CharField(max_length=50)
    contraseña=models.CharField(max_length=50, default='SOME STRING')
    institucion = models.CharField(max_length=50)


class Benefactor(models.Model):
    idBenefactor = models.CharField(max_length=10,primary_key=True)
    nombre_benefactor = models.CharField(max_length=50)

class Beneficio(models.Model):
    idBeneficio = models.CharField(max_length=10,primary_key=True)
    nombre_beneficio = models.CharField(max_length=50)

class Beneficiario(models.Model):
    idBeneficiario = models.AutoField(primary_key=True)
    direccion=models.CharField(max_length=50, default='SOME STRING')
    departamento = models.ForeignKey(Departamento, null = True, blank = True, on_delete=models.CASCADE)
    municipio = models.ForeignKey(Municipio, null = True, blank = True, on_delete=models.CASCADE)  
    estado = models.IntegerField(default=1)
    
class DetalleBeneficiario(models.Model):
    idDetalle = models.AutoField(primary_key=True)
    beneficiario = models.ForeignKey(Beneficiario, null = True, blank = True, on_delete=models.CASCADE)  
    beneficio = models.ForeignKey(Beneficio, null = True, blank = True, on_delete=models.CASCADE)
    benefactor = models.ForeignKey(Benefactor, null = True, blank = True, on_delete=models.CASCADE)
    cantidad = models.CharField(max_length=10)
    

ardc/core/forms.py
from django import forms

from .models import Departamento, Municipio, Beneficio, Benefactor


class FormFiltrar(forms.Form):

    departamento = forms.ModelChoiceField(
        label=u'', 
        queryset=Departamento.objects.all(),
        widget=forms.Select(attrs={'class':'form-control'}),
    )
    
    municipio = forms.ModelChoiceField(
        label=u'', 
        queryset=Municipio.objects.all(),
        widget=forms.Select(attrs={'class':'form-control'}),
    )

    ayudas = forms.ModelChoiceField(
        label=u'', 
        queryset=Beneficio.objects.all(),
        widget=forms.Select(attrs={'class':'form-control'}),
    )

    entidades = forms.ModelChoiceField(
        label=u'', 
        queryset=Benefactor.objects.all(),
        widget=forms.Select(attrs={'class':'form-control'}),
    )

    def __init__(self, *args, **kwargs):
        super(FormFiltrar, self).__init__(*args, **kwargs)
        self.fields['municipio'].queryset = Municipio.objects.none()

ardc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Departamento, Municipio, Beneficio, Benefactor, Beneficiario, DetalleBeneficiario
from .forms import FormFiltrar
from django.db import connection


from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm #Crea un login a partir de django
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from django.shortcuts import redirect

# Create your views here.
"""
Filtrar Datos/
Iniciar Sesion/
Agregar Informacion/
"""

#Obtiene todos los registros de un modelo 
departamentos = Departamento.objects.all()
municipios = Municipio.objects.all()
ayudas = Beneficio.objects.all()
entidades = Benefactor.objects.all()

def filtrar(request): #request:es la peticion
   #Obtiene los objetos de la base de datos 
    beneficiarios = Beneficiario.objects.raw('SELECT idBeneficiario, direccion, nombre_departamento, nombre_municipio, COUNT(idBeneficiario) AS cantidad '\
                                        'FROM core_beneficiario, core_municipio, core_departamento, core_detallebeneficiario  '\
                                        'WHERE core_beneficiario.municipio_id=core_municipio.idMunicipio  '\
                                        'AND core_beneficiario.departamento_id=core_departamento.idDepartamento  '\
                                        'AND core_beneficiario.idBeneficiario=core_detallebeneficiario.beneficiario_id '\
                                        'GROUP BY direccion, nombre_departamento, nombre_municipio, idBeneficiario')
    #Obtiene los objetos de la base de datos para el grafico 
    grafico = Departamento.objects.raw('SELECT idDepartamento, nombre_departamento, count(departamento_id) cont FROM core_departamento  '\
                                        'left outer join core_beneficiario on core_beneficiario.departamento_id = core_departamento.idDepartamento  '\
                                        'left join core_detallebeneficiario on core_beneficiario.idBeneficiario = core_detallebeneficiario.beneficiario_id '\
                                        'group by nombre_departamento, idDepartamento '\
                                        'order by nombre_departamento ASC')
    #Formulario
    form = FormFiltrar()
    if request.method == 'POST': #Si hace una peticion hace un cambio en la base de datos
        form = FormFiltrar(request.POST)
        if form.is_valid(): # si el formulario es valido
            # Guardar los datos
            #url = reverse('home')
            return HttpResponseRedirect(url) #redireccione 
    return render(request, "core/filtrar.html",{'form':form, 'ayudas':ayudas, 'entidades':entidades, 'beneficiarios':beneficiarios, 'grafico':grafico})


#def iniciar(request):
#    return render(request, "core/iniciar.html")


def agregar(request):
    form=FormFiltrar()
    idBenefic = 0
    consulta = 'SELECT idBeneficiario, MAX(idBeneficiario) id FROM core_beneficiario WHERE estado = 1 GROUP BY idBeneficiario'
    results = Beneficiario.objects.raw(consulta)
    for result in results:
        idBenefic = result.idBeneficiario

    if  results:
        return redirect('../detalle/')
    else:
        if request.method=="POST":
            #creacion de objetos
            beneficiario=Beneficiario()       
            
            direccion=request.POST['direccion']
            #Como para tener identificados los datos y que se van a guardar en la tabla
            beneficiario.direccion=direccion
            
            #QuerySets que lee de la base de datos
            municipio=Municipio.objects.get(idMunicipio=request.POST['municipio']) #Consigue un objeto que tenga cualquier id del municipio
            departamento=Departamento.objects.get(idDepartamento=request.POST['departamento'])
            beneficiario.departamento=departamento
            beneficiario.municipio=municipio      
            #Guarda en la base de datos
            beneficiario.save()

            return redirect('../detalle/')

            # Añadimos los datos recibidos al formulario
            form=FormFiltrar(request.POST)
            if form.is_valid():
                return HttpResponse(url)  #devuelve un codigo (html)
    
    #me devuelve la peticion y la template  donde muestro el contexto
        return render(request, "core/agregar.html",{'form':form})

def detalleBeneficiario(request):
    #Obteniendo los objetos de ayuda y entidades 
    ayudas = Beneficio.objects.all()
    entidades = Benefactor.objects.all()
    
    #Crea Objeto detalle beneficiario
    detalle=DetalleBeneficiario()
    idBenefic = 0
    consulta = 'SELECT idBeneficiario, MAX(idBeneficiario) id FROM core_beneficiario WHERE estado = 1 GROUP BY idBeneficiario'
     #Devuelve los objetos de la base de datos 
    results = Beneficiario.objects.raw(consulta)
    for result in results:
        idBenefic = result.idBeneficiario
    
    if results:

        if request.method=="POST":
            #Querysets que lee de la base de datos 
            detalle.beneficio=Beneficio.objects.get(idBeneficio=str(request.POST['ayuda']))
            detalle.benefactor=Benefactor.objects.get(idBenefactor=str(request.POST['entidades']))
            detalle.beneficiario=Beneficiario.objects.get(idBeneficiario=str(idBenefic))
            detalle.cantidad=request.POST['cantidad']

            detalle.save()
        
        return render(request, "core/agregar-detalle.html",{'ayudas':ayudas, 'entidades':entidades})

    else :
        return redirect('/')


def actualizar(request):
    idBenefic = 0
    consulta = 'SELECT idBeneficiario, MAX(idBeneficiario) id FROM core_beneficiario WHERE estado = 1 GROUP BY idBeneficiario'
    results = Beneficiario.objects.raw(consulta)
    for result in results:
        idBenefic = result.idBeneficiario
    
    contador = 0
    consulta = 'SELECT idDetalle FROM core_detallebeneficiario WHERE beneficiario_id = %s' % (idBenefic)
    results2 = DetalleBeneficiario.objects.raw(consulta)
    for result in results2:
        contador += 1
    
    if contador == 0:
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM core_beneficiario WHERE idBeneficiario = %s", [idBenefic])
    else:
        with connection.cursor() as cursor:
            cursor.execute("UPDATE core_beneficiario SET estado = 0 WHERE idBeneficiario = %s", [idBenefic])

    return redirect('/')

#Esta funcion lo que hace es crear el login del ususario encuestador 
def login(request):
    if request.user.is_authenticated:
        return redirect('/')
    else :
        # Creamos el formulario de autenticación vacío
        form = AuthenticationForm()
        if request.method == "POST":
            # Añadimos los datos recibidos al formulario
            form = AuthenticationForm(data=request.POST)
            # Si el formulario es válido...
            if form.is_valid():
                # Recuperamos las credenciales validadas
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']

                # Verificamos las credenciales del usuario
                user = authenticate(username=username, password=password)

                # Si existe un usuario con ese nombre y contraseña
                if user is not None:
                    # Hacemos el login manualmente
                    do_login(request, user)
                    # Y le redireccionamos a la portada
                    return redirect('../')

        # Si llegamos al final renderizamos el formulario
        return render(request, "core/iniciar.html", {'form': form})

def logout(request): #Cerrar Sesion
    # Redireccionamos a la portada
    do_logout(request)
    return redirect('/')

ardc/core/templates/core/agregar-detalle.html
{% extends 'core/base.html' %}

{% block title %}Agregar Información{% endblock %}

{% block background %}{% load static %}{% static 'core/img/portfolio-bg.jpg' %}{% endblock %}

{% block headers %}
<h1>Agregar Información</h1>
<span class="subheading">Debe de ingresar datos correctos</span>
{% endblock %}

{% block content %}
<!---Aqui empezar-->
<div align="center">
  <img class="img-fluid" src="{% static 'core/img/logo_new.png' %}" alt="">
</div>

<div class="container">
  <div class="container">
    <form method="POST">
        {% csrf_token %}
        <br>
        <p>
        <h4>Agregar ayuda:</h4>
        </p>
        <br>
        <!--Formulario para tipo de ayuda-->

        <div class="row">
            <div class="col">
                <label class="col-form-label" for="inputAyuda"><h5>Tipo de Ayuda:</h5></label>
                <select class="form-control" name="ayuda" id="id_beneficio">
                    {% for ayuda in ayudas %}
                    <option value = {{ayuda.idBeneficio}}>{{ayuda.nombre_beneficio}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <label class="col-form-label" for="inputEntidad"><h5>Entidad:</h5></label>
                <select class="form-control"  name="entidades" id="id_benefactor">
                    {% for entidad in entidades %}
                    <option value = {{entidad.idBenefactor}}>{{entidad.nombre_benefactor}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                <label class="col-form-label" for="inputCantidad"><h5>Cantidad</h5></label>
                <input type="text" class="form-control" required pattern="[0-9]{1,4}" placeholder="Introduzca la cantidad"  name="cantidad" id="inputCantidad">
                </div>
            </div>
        </div>
        
        <!--Botones de accion-->
        <br></br>
        <div class="container">
            <div align="center" class="container">
            <a href="{% url 'actualizar' %}"><button type="button" class="btn btn-primary">
                <h4>Terminar</h4>
                </button></a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <button type="submit" class="btn btn-dark" id="agregar">
                <h4>Agregar</h4>
            </button>
            </div>
        </div>
    </form>
    <br>
    <p>
    </p>
    <br>

    <div id="result">

    </div>

    <script type="text/javascript">
    getID();
    $(document).ready(function() {
        $("#agregar").on("click", getID);
    });

    function getID() {
        
        $("#result").html("");
        var request = $.ajax({
            type: "GET",
            url: "{% url 'get_last' %}",
        });
        request.done(function(response) {
            getInfor(response.idLast);
        }); 
    }

    function getInfor(idLast) {
        $("#result").html(""); //RESETEA
        var request = $.ajax({
            type: "GET",
            url: "{% url 'get_detalle' %}",
            data: {
                "beneficiario_id": idLast,
            },
        });
        request.done(function(response) {
            // Agregamos los resultados al select
            $("#result").html(response.detallesExtend);
            $("#result").trigger("click");
            
        }); 
    }

    

</script>
  </div>

  {% endblock%}

  {% block footer%}

  {% endblock %}

ardc/core/templates/core/agregar.html
{% extends 'core/base.html' %}

{% block title %}Agregar Información{% endblock %}

{% block background %}{% load static %}{% static 'core/img/portfolio-bg.jpg' %}{% endblock %}

{% block headers %}
<h1>Agregar Información</h1>
<span class="subheading">Debe de ingresar datos correctos</span>
{% endblock %}

{% block content %}
<!---Aqui empezar-->
<div align="center">
  <img class="img-fluid" src="{% static 'core/img/logo_new.png' %}" alt="">
</div>

<div class="container">
  <form method="POST">
    {% csrf_token %}

    <!--Formulario para residencia-->
    <div class="container">

      <fieldset>
        <div class="form-group">
          <label class="col-form-label" for="inputDireccion">
            <h5>Dirección:</h5>
          </label>
          <input type="text" class="form-control" required placeholder="Introduzca su direccion"  name="direccion" id="inputDireccion">
        </div>
      </fieldset>

      <div class="row">
        <div class="col">
          <label class="col-form-label" for="inputDepartamento">
            <h5>Departamento:</h5>
          </label>
          {{form.departamento.label_tag}}
          {{form.departamento}}
        </div>
        <div class="col">
          <label class="col-form-label" for="inputMunicipio">
            <h5>Municipio:</h5>
          </label>
          {{form.municipio.label_tag}}
          {{form.municipio}}
        </div>
      </div>


      <script type="text/javascript">

        $(document).ready(function () {
          $("#id_departamento").on("change", getMunicipios);
          $("#filtrarInfo").on("click", getInfo);
        });

        function getMunicipios() {
          var departamentoId = $("#id_departamento").val();
          if (departamentoId) {
            // Eliminamos las opciones anteriores del select
            $("#id_municipio").html("");
            var request = $.ajax({
              type: "GET",
              url: "{% url 'get_municipios' %}",  // va a traer los datos de la funcion get_municipios 
                           data: {
                "departamento_id": departamentoId, //segun el departamento
              },
            });
            request.done(function (response) {
              // Agregamos los resultados al select
              $("#id_municipio").html(response.municipios);
              $("#id_municipio").trigger("change");
            });
          } else {
            $("#id_municipio").html("<option value='' selected='selected'>--------</option>"); //si no los ha encontrado queda ------
            $("#id_municipio").trigger("change");
          }
        }

      </script>
    </div>

    <br>
    <p>
      
      <!--Botones de accion-->
      <br></br>
    <div class="container">
      <div align="center" class="container">
        <a href="{% url 'Filtrar' %}"><button type="button" class="btn btn-primary">
            <h4>Cancelar</h4>
          </button></a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-dark">
          <h4>Siguiente</h4>
        </button>
      </div>
    </div>
  </form>
</div>

  {% endblock%}

  {% block footer%}

  {% endblock %}

ardc/core/templates/core/filtrar.html
{% extends 'core/base.html' %}

{% block title %}Filtracion{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}
<h1>Encuesta</h1>
    <span class="subheading">Gestor de información</span>
{% endblock %}

{% block content %}
<!--Imagen del logotipo de la app-->
    <div align = "center">
        <img class="img-fluid" src="{% static 'core/img/logo_new.png' %}" alt="">
    </div>

<!--Informacion sobre la app y sobre lo que trata-->
    <div align = "Center">
        <div class="container">
             <label>
                  <h4>
                        Esta aplicación conlleva a que las personas brinden información acerca de lo que recibieron,
                        y que entidades les ayudaron para sobrellevar la cuarentena que está pasando en este momento, 
                        debido a los motivos que se está enfrentando todo el país de El Salvador.
                  </h4>
                    <br>
                  <h4> 
                        La idea es crear una herramienta de fácil utilidad para que cualquier persona pueda acceder 
                        sus datos sin salir de casa, y para que las instituciones que necesitan esta información
                        sea de utilidad para ellos. 
                  </h4>
             </label>
        </div>
        <br>
    </div>
    <br>

<!--Filtrado de datos-->
    <div class = "container">
        <label><h4>Filtrar Datos por:</h4></label>
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <label class="col-form-label" for="inputDepartamento"><h5>Departamento:</h5></label>
                    {{ form.departamento.label_tag }} 
                    {{ form.departamento }}
                    
                </div>
                <div class="col">
                    <label class="col-form-label" for="inputMunicipio"><h5>Municipio:</h5></label>
                    {{ form.municipio.label_tag }}  
                    {{ form.municipio }}
                    
                </div>

                <button type="button" class="btn btn-dark" id="filtrarInfo"><h8>Filtrar</h8></button>
            </div>
        </form>

        <br>
        <div id='result'>
            <table class="table table-hover">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">Direccion</th>
                        <th scope="col">Departamento</th>
                        <th scope="col">Municipio</th>
                        <th scope="col">Cantidad de Ayudas</th>
                        <th scope="col">Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for beneficiario in beneficiarios %}
                        <tr class="table-light">    
                            <td>{{beneficiario.direccion}}</td>
                            <td>{{beneficiario.nombre_departamento}}</td>
                            <td>{{beneficiario.nombre_municipio}}</td>
                            <td>{{beneficiario.cantidad}}</td>
                            <td>
                                <button type="button" onclick="getInfoExtend({{beneficiario.idBeneficiario}})" class="btn btn-link" data-toggle="modal" data-target="#exampleModal">
                                    <i class="large material-icons">more</i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>   

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Información detallada</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="false">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="result2">
                            
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div id="container"></div>
                </div>
            </div>
        </div>
        
        <script type="text/javascript">

            $(document).ready(function() {
                $("#id_departamento").on("change", getMunicipios);
                $("#filtrarInfo").on("click", getInfo);
                $('#myModal').on('shown.bs.modal', function () {
                    $('#myInput').trigger('focus')
                })
            });

            function getMunicipios() {
                var departamentoId = $("#id_departamento").val();
                if (departamentoId) {
                    // Eliminamos las opciones anteriores del select
                    $("#id_municipio").html("");
                    var request = $.ajax({
                        type: "GET",
                        url: "{% url 'get_municipios' %}",
                        data: {
                            "departamento_id": departamentoId,
                        },
                    });
                    request.done(function(response) {
                        // Agregamos los resultados al select
                        $("#id_municipio").html(response.municipios);
                        $("#id_municipio").trigger("change");
                    });
                } else {
                    $("#id_municipio").html("<option value='' selected='selected'>--------</option>");
                    $("#id_municipio").trigger("change");
                }
            }

            function getInfo() {
                var departamentoId = $("#id_departamento").val();
                var municipioId = $("#id_municipio").val();
                var beneficioId = $("#id_beneficio").val();
                var benefactorId = $("#id_benefactor").val();

                $("#result").html("");
                var request = $.ajax({
                    type: "GET",
                    url: "{% url 'get_info' %}",
                    data: {
                        "departamento_id": departamentoId,
                        "municipio_id": municipioId,
                        "beneficio_id": beneficioId,
                        "benefactor_id": benefactorId,
                    },
                });
                request.done(function(response) {
                    // Agregamos los resultados al select
                    $("#result").html(response.beneficiarios);
                    $("#result").trigger("click");
                }); 
                setTimeout('getInfo()',10000);
            }

            function getInfoExtend(id_beneficiario) {
                $("#result2").html("");
                var request = $.ajax({
                    type: "GET",
                    url: "{% url 'get_detalle' %}",
                    data: {
                        "beneficiario_id": id_beneficiario,
                    },
                });
                request.done(function(response) {
                    // Agregamos los resultados al select
                    $("#result2").html(response.detallesExtend);
                    $("#result2").trigger("click");
                }); 
            }

            Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Cantidad de ayuda por departamento'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                categories: [
                    {% for grafic in grafico %}
                    '{{grafic.nombre_departamento}}',
                    {% endfor %}
                ],
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Ayuda'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f}</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Cantidad de ayuda',
                showInLegend: false,
                colorByPoint : true,
                data: [
                    {% for grafic in grafico %}
                    {{grafic.cont}},
                    {% endfor %}
                ]

            }]
        });
        </script>
       
    </div>    
{% endblock%}

<!--Aquí se va a insertar la tabla que muestra los datos (La tabla principal)
Dicha tabla contiene [Departamento, Municipio, Beneficio, Benefactor]-->





{% block footer%}
    <br></br>
    <div align = "center" class="container">
        {% if not request.user.is_authenticated %}
        <a href="{% url 'Iniciar Sesion' %}"><button type="button" class="btn btn-link" pull-righ>Iniciar Sesión</button></a> 
        {% endif%}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <label>Si desea agregar información, Haga click Aquí</label>
        <a href="{% url 'Agregar Infromacion' %}"><button type="button" class="btn btn-dark" pull-left><h8>Aquí</h8></button></a>
    </div>
{% endblock %} 

ardc/core/templates/core/iniciar.html
{% extends 'core/base.html' %}

{% block title %}Iniciar Sesión{% endblock %}

{% block background %}{% load static %}{% static 'core/img/iniciar.jpg' %}{% endblock %}

{% block headers %}
<h1>Bienvenido a Iniciar Sesion</h1>
    <span class="subheading">Debe de ingresar datos correctos</span>
{% endblock %}
<!--Contenido-->
{% block content %}
    <div class="row project">  	
        <div class="col-lg-3 col-md-4 offset-lg-1">
            <img class="img-fluid" src="{% static 'core/img/logo_new.png' %}" alt="">
        </div>
        <div class="col-lg-7 col-md-8">
            <h2 class="section-heading title">ARDC</h2>   
            <h2>Iniciar sesión</h2>

            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <div class="container">
                    <div align="center" class="container">
                        <a href="{% url 'Filtrar' %}"><button type="button" class="btn btn-warning"><h4>Cancelar</h4></button></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <button type="submit" class="btn btn-success"><h4>Iniciar Sesión</h4></button>
                     </div>
                </div>
            </form>

            <hr />
        </div>
    </div>
{% endblock%}

{% block footer%}
    <br></br>

{% endblock %}